### ISSUE TITLE
Unable to update state

### ISSUE THREAD

**Issue by LeChat109** [svmironov/aircloud_ha#11]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:696
First occurred: 2 novembre 2023 à 10:13:36 (57 occurrences)
Last logged: 09:44:35

Update for climate.chambre fails
Update for climate.sejour fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 696, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/air_cloud/climate.py", line 233, in update
    devices = self._api.load_climate_data()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/air_cloud/api.py", line 57, in load_climate_data
    response = ws.recv()
               ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_core.py", line 364, in recv
    opcode, data = self.recv_data()
                   ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_core.py", line 387, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_core.py", line 408, in recv_data_frame
    frame = self.recv_frame()
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_core.py", line 447, in recv_frame
    return self.frame_buffer.recv_frame()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_abnf.py", line 340, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.11/site-packages/websocket/_abnf.py", line 296, in recv_header
    header = self.recv_strict(2)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_abnf.py", line 375, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_core.py", line 531, in _recv
    return recv(self.sock, bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/websocket/_socket.py", line 124, in recv
    raise WebSocketConnectionClosedException(
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.

**Comment by svmironov** [comment]
Hi! 
The API consists of 2 modules, REST for sending commands and a web socket for receiving status. The web socket has been unstable for a long time, but unfortunately, sending a command requires an ID that can only be extracted from the status. But at the same time, if you did not reboot, HA integration may continue to work, since device identifiers are stored in the cache but without updating state.
