### ISSUE TITLE
aircloud fails to initialize

### ISSUE THREAD

**Issue by dajomas** [svmironov/aircloud_ha#20]
Python version: 3.12.2
HA Core version: 2024.2.0
aircloud_ha: v2.0.1 (checked out tag v2.0.1)

I installed aircloud_ha by cloning the repository to my HA Core system (NOT using HACS), and then symlinking the custom_components/aircloud directory to custom_componentns/aircloud in my config directory, next I editted my configuration.yaml:
```yaml
air_cloud:
  email: "!secret aircloud_account"
  password: "!secret aircloud_password"

climate:
  - platform: air_cloud
```
and added the correct values to my secrets.yaml

When I restart home assistant, the following messages appear in the logfile:
```
2024-02-21 12:10:13.901 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing air_cloud/diagnostics.py
Traceback (most recent call last):
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.aircloud.diagnostics'
2024-02-21 12:10:13.902 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing air_cloud/recorder.py
Traceback (most recent call last):
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.aircloud.recorder'
2024-02-21 12:10:13.903 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing air_cloud/group.py
Traceback (most recent call last):
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.aircloud.group'
2024-02-21 12:10:14.068 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing air_cloud/logbook.py
Traceback (most recent call last):
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.aircloud.logbook'
2024-02-21 12:10:14.072 ERROR (MainThread) [homeassistant.helpers.integration_platform] Unexpected error importing air_cloud/system_health.py
Traceback (most recent call last):
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/loader.py", line 847, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/HASS-2024.2.0/lib/python3.12/site-packages/homeassistant/loader.py", line 864, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/Python-3.12.2/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.aircloud.system_health'
```

Can you please help out here?

**Comment by dajomas** [comment]
Okay, I made a typo in my password and I was able to add the custom component BUT it still gave the errors about missing modules.

However, after succesfully loggin on, my airco does not show up.

I also tried to remove the configuration from configuration.yaml and add via the UI but this is what the configuration window looks like:
![image](https://github.com/svmironov/aircloud_ha/assets/5916945/fe4ad37a-7768-4874-8179-df82b3c7f686)

I guess, the first field is my email addres, the second is my password and the third is the temperature offset

**Comment by dajomas** [comment]
And I found out why the Airco did not show up:
I invited an account especially for  HA, but when I created that account, it also created a default space for that account. The airco is not in that space but in the space from my main account (from which I invited the HA specific account).

By default, the space for an account is selected and since there is no airco in that account, no airco is displayed.

In the AirCloud app, when I log in, I don't see the airco until I select the Space from the main account.

When I used my main account in the aircloud_ha integration, my airco did show up.

**Comment by dajomas** [comment]
Sadly, I had to disable aircloud_ha because it ate up my CPU (going to 100% and halting the working of HA)

**Comment by dajomas** [comment]
I found the issue: your domain is ```air_cloud``` but the custom_components directory is ```aircloud```

When you rename the directory to ```air_cloud``` all issues are solved

**Comment by dajomas** [comment]
I was a bit too soon, the errormessages are gone but the 100% CPU usage came back again. It takes a while but suddenly, it is there. When I remove the integration the 100% CPU does not come back

I discovered that the 100%CPU starts right after this message in the logfile:
```
2024-02-22 12:22:24.788 WARNING (MainThread) [homeassistant.components.climate] Updating air_cloud climate took longer than the scheduled update interval 0:01:00
```

So I turned debugging on for aircloud and did not find additional messages right before the 100%CPU

**Comment by svmironov** [comment]
Hi! Thank for your debug. I added small fix. It will be to work. Please fix it

**Comment by dajomas** [comment]
I have been testing and the problem was that once the authentication failed, the connection would not be made succesfully any more. So I made made some small changes in ```api.py``` and it now works fine:

function ```__refresh_token```:
```python
    async def __refresh_token(self, forced=False):
        now_datetime = datetime.now()
        td = now_datetime - self._last_token_update
        td_minutes = divmod(td.total_seconds(), 60)

        if self._token is None or forced:
            await self.__authenticate()
        elif td_minutes[1] > 5:
            async with self._session.post(HOST_API + URN_REFRESH_TOKEN,
                                          headers={"Authorization": "Bearer " + self._ref_token,
                                                    "isRefreshToken": "true"}) as response:
                await self.__update_token_data(await response.json())
            self._last_token_update = now_datetime
```

function ```load_climate_data```:
```python
    async def load_climate_data(self):
        await self.__refresh_token()
        async with self._session.ws_connect(URN_WSS, timeout=60) as ws:  # Add a timeout value (in seconds) here
            CONNECT_STRING = "CONNECT\naccept-version:1.1,1.2\nheart-beat:10000,10000\nAuthorization:Bearer {}\n\n\0\nSUBSCRIBE\nid:{}\ndestination:/notification/{}/{}\nack:auto\n\n\0"
            CONNECT_STRING = CONNECT_STRING.format(self._token, str(uuid.uuid4()), str(self._family_id), str(self._family_id))
            await ws.send_str(CONNECT_STRING)

            try:
                attempt = 0
                max_attempts = 10
                while attempt < max_attempts:
                    attempt += 1
                    msg = await asyncio.wait_for(ws.receive(), timeout=10)
                    if msg.type == WSMsgType.TEXT:
                        if msg.data.startswith("CONNECTED") and "user-name:" not in msg.data:
                            _LOGGER.warning("Websocket connection failed. Re-authenticating.")
                            await ws.close()
                            await self.__refresh_token(forced=True)
                            await ws.send_str(CONNECT_STRING)
                            attempt = 0
                        elif msg.data.startswith("MESSAGE") and "{" in msg.data:
                            response = msg.data
                            break
                    elif msg.type == WSMsgType.CLOSED:
                        _LOGGER.warning("WebSocket connection is closed.")
                        return None
                else:
                    _LOGGER.warning("Unable to find '{' symbol after {} attempts".format(max_attempts))
                    await ws.close()
                    return None
            except asyncio.TimeoutError:
                _LOGGER.warning("WebSocket connection timed out while receiving data")
                await ws.close()
                return None

        _LOGGER.debug("AirCloud climate data: " + str(response))
        message = "{" + response.partition("{")[2].replace("\0", "")
        struct = json.loads(message)
        return struct["data"]
```

In addition, the directory in custom_components should be ```air_cloud``` (same as the domain name)

**Comment by svmironov** [comment]
Ok. I added your code to new release. Thank you!
