### ISSUE TITLE
Error KeyError: 'token'

### ISSUE THREAD

**Issue by IncognitoMSK** [svmironov/aircloud_ha#3]
Logger: homeassistant.components.climate
Source: custom_components/air_cloud/api.py:31
Integration: Климат ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 13:24:57 (1 occurrences)
Last logged: 13:24:57

Error while setting up air_cloud platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/air_cloud/climate.py", line 46, in async_setup_platform
    await _async_setup(hass, async_add_entities)
  File "/config/custom_components/air_cloud/climate.py", line 41, in _async_setup
    devices = await hass.async_add_executor_job(api.load_climate_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/air_cloud/api.py", line 42, in load_climate_data
    self.__refresh_token()
  File "/config/custom_components/air_cloud/api.py", line 31, in __refresh_token
    self._token = response.json()["token"]
KeyError: 'token'

**Comment by svmironov** [comment]
Такая ошибка говорит, что не удалось получить токен авторизации, вероятно нервные пароль или логин
